name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main   # main 브랜치에 push될 때마다 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - uses: actions/checkout@v4

      # 2. Node.js 설치
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. 의존성 설치
      - run: npm ci

      # 4. 빌드
      - run: npm run build

      # 5. GitHub Pages 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out        # 빌드 결과물
          publish_branch: gh-pages  # 배포용 브랜치
          # destination_dir: wedding-invitation
